import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { data } from '../lib/fake/data'

import SearchBar from '../components/SearchBar/SearchBar';
import isInSubs from '../components/utils/isInSubs';
import { useRouter } from 'next/router'



export default function Home() {
  
  const router = useRouter();



  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.heading}>Zeddit</h1>
          <SearchBar />
        </div>
      </main>
    </>
  )
}
